var $window=$(window);var windowsize=$window.width();var lazyLoadInstance=new LazyLoad({elements_selector:".lazy"});$(window).on("load",function(){$('.poster').show();});localStorage.removeItem('CHANGE_VIDEO');$('.my-tooltip').click(function(){$('.tooltiptext').fadeToggle();});$.ajax({'url':$('meta[name="website"]').attr('content')+'/ads-under-menus','method':'get','success':function(res){if(res){if(windowsize<973){var url=$('meta[name="website"]').attr('content')+'/'+res[0].small_image;var img='<img alt="khmermov ads" class="img-fluid" src="'+url+'">';}else{var url=$('meta[name="website"]').attr('content')+'/'+res[0].image;var img='<img alt="khmermov ads" class="img-fluid" src="'+url+'">'}
var asdLink=res[0].url;if(res[0].url=='#'){var link='<a href="#">'+img+'</a>';}else{var link='<a target="_blank" href="'+asdLink+'">'+img+'</a>';}
$('#ads-under-menus').html(link);}}});$.ajax({'url':$('meta[name="website"]').attr('content')+'/ads-top-logo','method':'get','success':function(res){if(res){if(windowsize<768){var url=$('meta[name="website"]').attr('content')+'/'+res.small_image;var img='<img alt="khmermov ads" class="img-fluid" src="'+url+'">';}else{var url=$('meta[name="website"]').attr('content')+'/'+res.image;var img='<img alt="khmermov ads" class="img-fluid" src="'+url+'">'}
var asdLink=res.url;if(res.url=='#'){var link='<a href="#">'+img+'</a>';}else{var link='<a target="_blank" href="'+asdLink+'">'+img+'</a>';}
$('#ads-top-logo').html(link);}}});$.ajax({'url':$('meta[name="website"]').attr('content')+'/ads-footer-fixed','method':'get','success':function(res){if(res[0]){if(windowsize<973){var url=$('meta[name="website"]').attr('content')+'/'+res[0].small_image;var img='<img alt="khmermov ads" class="img-fluid" src="'+url+'">';}else{var url=$('meta[name="website"]').attr('content')+'/'+res[0].image;var img='<img alt="khmermov ads" class="img-fluid" src="'+url+'">'}
var asdLink=res[0].url;if(res[0].url=='#'){var link='<a href="#">'+img+'</a>';}else{var link='<a target="_blank" href="'+asdLink+'">'+img+'</a>';}
$('#ads-footer-fixed .show').html(link);}}});$('.hide-footer-fixed').click(function(){$('#ads-footer-fixed').find('.show').toggleClass('hide-footer-fixed-ads');if($('#ads-footer-fixed').find('.show').hasClass('hide-footer-fixed-ads')){$('.hide-footer-fixed').find('i').removeClass('fa-caret-down');$('.hide-footer-fixed').find('i').addClass('fa-caret-up');}else{$('.hide-footer-fixed').find('i').addClass('fa-caret-down');$('.hide-footer-fixed').find('i').removeClass('fa-caret-up');}});$('document').ready(function(){$('.marquee').css('opacity','1');if(windowsize<973){var duration=9000;}else{var duration=20000;}
$('.marquee').marquee({duration:duration,});});$.ajaxSetup({headers:{'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')}});function delay(callback,ms){var timer=0;return function(){var context=this,args=arguments;clearTimeout(timer);timer=setTimeout(function(){callback.apply(context,args);},ms||0);};}
$('#input-search').on('keyup',function(e){$('.load-container').fadeIn();$("#search-data").html('');});$('#input-search').on('keyup',delay(function(e){if(!this.value){$('.search-dropdown').hide();$('.search-dropdown .loading').hide();$(".search-dropdown .data-dropdown").html('');$('.load-container').hide();return;}
$.ajax({'url':$('meta[name="website"]').attr('content')+'/movie/search','method':'post','data':{'search':this.value},'success':function(res){$('.search-dropdown').show();$('#search-data').show();$('.search-dropdown .loading').hide();$('.load-container').hide();if(res.data=='No data'){$("#search-data").html('<b class="display-5 text-white">No Data</b>');}else{$("#search-data").html(res.data);}}});},2000));$('#support-us').click(function(){$.ajax({'url':$('meta[name="website"]').attr('content')+'/support-us','method':'post','data':{'click':1},'success':function(res){}});});$('#close-search-box').click(function(){$('.search-content').fadeOut();$('.search-dropdown').hide();$('.search-dropdown .loading').hide();$(".search-dropdown .data-dropdown").html('');$('#input-search').val('');});$(".btn-search").click(function(){$('.search-content').fadeIn();$('#input-search').focus();$('.mobile-nav-background').closest('nav').find('#navbarSupportedContent').removeClass('showNav');$('.mobile-nav-background').addClass('d-none');});$('.storyline i.show-more').click(function(){$('.text-story').css({'height':'auto'});$(this).hide();$('.storyline i.show-less').show();});$('.storyline i.show-less').click(function(){$('.text-story').css({'height':'170px'});$(this).hide();$('.storyline i.show-more').show();});$(".navbar-toggler").click(function(){$(".mobile-nav-background").toggleClass('d-none');$("#navbarSupportedContent").toggleClass('showNav');});$(".mobile-nav-background").click(function(){$(this).closest('nav').find('#navbarSupportedContent').removeClass('showNav');$(this).addClass('d-none');});$('.ad-movie-popup i').click(function(){$('.ad-movie-popup').hide();});